### ISSUE TITLE
please correct this

### ISSUE THREAD

**Issue by swappyison** [pratikpatel8982/yt-dlp-mp4decrypt#1]
yt-dlp --use-postprocessor MP4Decrypt:decryption_key=56d1c5557f265bd3b80f0afa811b721a:f92d06c9aa6ec14aabc00415dacf4dbd "https://jc-ak-dashstreaming.jiocinema.com/content/entry/wvdata/8/57/05c6776002ab11ee99f13569c11f93ca_voot_web_premium.mpd?hdnts=st=1693328488~exp=1693329088~acl=/content/entry/wvdata/8/57/*~id=cb39d4e1-3840-4b39-84df-f2c9639bdd44~hmac=261711f6e6bbad38fdafa4b689826422f4bb967df2319923f2e6a80b35eeae1a"

**Comment by pratikpatel8982** [comment]
Try using --allow-u
