### ISSUE TITLE
how to find the key for decryption

### ISSUE THREAD

**Issue by parvinders347** [pratikpatel8982/yt-dlp-mp4decrypt#2]
But where i can find the decryption keys? i wanted to download the udemy video that uses mpd stream videos protected by widevine DRM

**Comment by timta8** [comment]
i now a site called getwvkeys.cc u can use that one but i also found this guide on
https://lxlit.dev/posts/cdm-tools/how-to/
does this helps

**Comment by pratikpatel8982** [comment]
You can refer to videohelp.com forums for help.
